name: Build_CSV

on:
  [repository_dispatch]

jobs:
  update-csv:
    if: github.event.action == 'update'
    runs-on: ubuntu-latest
    env:
      RESOURCE_NAME: ${{ github.event.client_payload.resourceName }}
      TRIGGER_REPO: ${{ github.event.client_payload.repo }}
      TRIGGER_SHA: ${{ github.event.client_payload.SHA }}
    steps:     
      - name: 'Event Information'
        run: |
          echo "Event '${{ github.event.action }}' for $RESOURCE_NAME received from $TRIGGER_REPO and commit sha $TRIGGER_SHA"

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v5

      - name: 'Setup Node Environment'
        uses: actions/setup-node@v5
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: 'Install Dependencies with Npm'
        run: |
          npm install -g npm@latest
          npm install

      - name: 'Extract CSVs'
        run: |
          npm run ${{ github.event.client_payload.resourceName }}

      - name: 'Setup git config'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: 'Commit changes'
        run: |
          RESP=$(git add $RESOURCE_NAME.csv -v)
          if [[ $RESP == "" ]]; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "$RESOURCE_NAME.csv updated by GitHub Actions triggered by $TRIGGER_REPO $TRIGGER_SHA"
            git push origin main
          fi