name: Build_CSV

on:
  [repository_dispatch]

env:
  NODE_VERSION: '14.x'

jobs:
  update-csv:
    if: github.event.action == 'update'
    runs-on: ubuntu-latest
    env:
      RESOURCE_NAME: ${{ github.event.client_payload.resourceName }}
      TRIGGER_REPO: ${{ github.event.client_payload.repo }}
      TRIGGER_REF: ${{ github.event.client_payload.ref }}
    steps:     
      - name: 'Event Information'
        run: |
          echo "Event '${{ github.event.action }}' for $RESOURCE_NAME received from $TRIGGER_REPO"

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2.3.4

      - name: 'Setup Node ${{ env.NODE_VERSION }} Environment'
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: 'Install Dependencies with Npm'
        run: |
          npm install -g npm@latest
          npm install

      - name: 'Extract CSVs'
        run: |
          npm run ${{ github.event.client_payload.resourceName }}

      - name: 'Setup git config'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: 'Commit changes'
        run: |
          git add $RESOURCE_NAME.csv
          git commit -m "$RESOURCE_NAME.csv updated by GitHub Actions triggered by $TRIGGER_REPO $TRIGGER_REF"
          git push origin main