name: CI_AutoMerge_Dependabot

on:
  pull_request:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - '**/README.md'
      - '**/dependabot.yml'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Setup Node Environment'
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: 'Install Dependencies with Npm'
        run: npm install

      - name: 'Extract and Diff Codelist CSV'
        # Should exit 1 (fail) if there is a difference - prevents dependabot automation from changing it live
        # If you're trying to merge a PR manually, make sure you commit the changes to codelists.csv
        run: |
          npm run codelists
          git diff --quiet codelists.csv 
      
      - name: 'Extract and Diff Ruleset CSV'
        # Should exit 1 (fail) if there is a difference - prevents dependabot automation from changing it live
        # If you're trying to merge a PR manually, make sure you commit the changes to rulesets.csv
        run: |
          npm run rulesets
          git diff --quiet rulesets.csv 

  automerge:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
